spring:
  
  application:
    name: checkin-survey-service
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${databasesurvey}
    username: ${usernamesurvey}
    password: ${passwordsurvey}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:      
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/spring-projects/spring-boot/issues/12007
    
security:
  oauth2:
    resource:
      id: 'authorization_api'
      jwk:
        key-set-uri: ${urlrac}/.well-known/openid-configuration/jwks    
    
survey:
  logurl: ${printurl}
      
server:
  port: 8080